[__config__]
httplib = 'httpx'

[camset]
source = 'pypi'
pypi = 'camset'

[desktop-privileges]
source = 'aur'
aur = 'desktop-privileges'
strip_release = true

[desktop-privileges-nogroups]
source = 'aur'
aur = 'desktop-privileges-nogroups'
strip_release = true

[digestif-git]
source = 'github'
github = 'astoff/digestif'
use_latest_tag = true

[hisat2]
source = 'github'
github = 'DaehwanKimLab/hisat2'
use_latest_release = true
prefix = 'v'

[jupyterlab-extension-ipycytoscape]
source = 'pypi'
pypi = 'ipycytoscape'

[jupyterlab-extension-jupyterlab_git]
source = 'pypi'
pypi = 'jupyterlab-git'

[jupyterlab-myst]
source = 'pypi'
pypi = 'jupyterlab-myst'

[libleidenalg]
source = 'github'
github = 'vtraag/libleidenalg'
use_latest_release = true

[nbopen]
source = 'pypi'
pypi = 'nbopen'

[otf-texgyre-pagella-math]
source = 'regex'
url = 'https://www.gust.org.pl/projects/e-foundry/tg-math/download/readme-tex-gyre-pagella-math.txt/at_download/file'
regex = 'Version: ([\d.]+)'

[python-adjusttext]
source = 'pypi'
pypi = 'adjusttext'

[python-aiomanhole]
source = 'pypi'
pypi = 'aiomanhole'

[python-alembic-autogenerate-enums]
source = 'pypi'
pypi = 'alembic-autogenerate-enums'

[python-altgraph]
source = 'pypi'
pypi = 'altgraph'

[python-anndata]
source = 'pypi'
pypi = 'anndata'

[python-anndata2ri]
source = 'pypi'
pypi = 'anndata2ri'

[python-array-api-compat]
source = 'pypi'
pypi = 'array-api-compat'

[python-asyncore-wsgi]
source = 'pypi'
pypi = 'asyncore-wsgi'

[python-conda]
source = 'github'
github = 'conda/conda'
use_latest_release = true

[python-conda-libmamba-solver]
source = 'github'
github = 'conda/conda-libmamba-solver'
use_latest_release = true

[python-connection_pool]
source = 'pypi'
pypi = 'connection-pool'

[python-entry-points-txt]
source = 'pypi'
pypi = 'entry-points-txt'

[python-falcon-cors]
source = 'pypi'
pypi = 'falcon-cors'

[python-fintech]
source = 'pypi'
pypi = 'fintech'

[python-fpdf]
source = 'pypi'
pypi = 'fpdf'

[python-get_version]
source = 'pypi'
pypi = 'get-version'

[python-hatch-docstring-description]
source = 'pypi'
pypi = 'hatch-docstring-description'

[python-headerparser]
source = 'pypi'
pypi = 'headerparser'

[python-ipynbname]
source = 'pypi'
pypi = 'ipynbname'

[python-itertools-len]
source = 'pypi'
pypi = 'itertools-len'

[python-jupyter_kernel_test]
source = 'pypi'
pypi = 'jupyter-kernel-test'

[python-legacy-api-wrap]
source = 'pypi'
pypi = 'legacy-api-wrap'

[python-leidenalg]
source = 'pypi'
pypi = 'leidenalg'

[python-loompy]
source = 'pypi'
pypi = 'loompy'

[python-louvain]
source = 'pypi'
pypi = 'python-louvain'

[python-louvain-igraph]
source = 'pypi'
pypi = 'louvain'

[python-mizani]
source = 'pypi'
pypi = 'mizani'

[python-mnnpy]
source = 'pypi'
pypi = 'mnnpy'

[python-modulegraph]
source = 'pypi'
pypi = 'modulegraph'

[python-ndjson-testrunner]
source = 'pypi'
pypi = 'ndjson-testrunner'

[python-numcodecs]
source = 'pypi'
pypi = 'numcodecs'

[python-plotnine]
source = 'pypi'
pypi = 'plotnine'

[python-profimp]
source = 'pypi'
pypi = 'profimp'

[python-pubchempy]
source = 'pypi'
pypi = 'pubchempy'

[python-pyefd]
source = 'pypi'
pypi = 'pyefd'

[python-pyjnius]
source = 'pypi'
pypi = 'pyjnius'

[python-pytest-pycharm]
source = 'pypi'
pypi = 'pytest-pycharm'

[python-qtico]
source = 'pypi'
pypi = 'qtico'

[python-requests_download]
source = 'pypi'
pypi = 'requests-download'

[python-reretry]
source = 'pypi'
pypi = 'reretry'

[python-rserve]
source = 'pypi'
pypi = 'pyrserve'

[python-sadisplay]
source = 'pypi'
pypi = 'sadisplay'

[python-scanpydoc]
source = 'pypi'
pypi = 'scanpydoc'

[python-scvelo]
source = 'pypi'
pypi = 'scvelo'

[python-session-info2]
source = 'pypi'
pypi = 'session-info2'

[python-smart-progress]
source = 'pypi'
pypi = 'smart-progress'

[python-spectate]
source = 'pypi'
pypi = 'spectate'

[python-sphinxcontrib-sadisplay]
source = 'pypi'
pypi = 'sphinxcontrib-sadisplay'
use_pre_release = true

[python-stdeb]
source = 'pypi'
pypi = 'stdeb'

[python-tbvaccine]
source = 'pypi'
pypi = 'tbvaccine'

[python-tikzplotlib-git]
source = 'pypi'
pypi = 'tikzplotlib'

[python-tiledb]
source = 'pypi'
pypi = 'tiledb'

[python-tuna]
source = 'pypi'
pypi = 'tuna'

[python-web-pdb]
source = 'pypi'
pypi = 'web-pdb'

[python-wheel-filename]
source = 'pypi'
pypi = 'wheel-filename'

[python-wheel-inspect]
source = 'pypi'
pypi = 'wheel-inspect'

[python-zarr]
source = 'pypi'
pypi = 'zarr'

[scanpy]
source = 'pypi'
pypi = 'scanpy'

[scanpy-scripts]
source = 'pypi'
pypi = 'scanpy-scripts'

[terrafirma]
source = 'github'
github = 'mrkite/TerraFirma'
use_latest_release = true

[twemoji-mozilla-fontconfig]
source = 'aur'
